# -*- coding: utf-8 -*-
"""cse422 lab 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12T62tO-ZxDMIczE9tGz81RFng1fLGvWR
"""

import heapq
graph = {}
hueristic = {}
with open("Input file.txt","r") as file:
  z = file.readlines()
  for i in range(len(z)):
    a = z[i].split()
    hueristic[a[0]] = int(a[1])
    temp = {}
    for j in range(2,len(a),2):
      temp[a[j]] = int(a[j+1])
    graph[a[0]] = temp
start = "Arad"
goal = "Bucharest"
heap = []
heapq.heapify(heap)
distance = {}
distance[start] = 0
heapq.heappush(heap,(hueristic[start],start))
path = []
parent = {}
parent[start] = 'Arad'
for key,value in graph.items():
  if len(heap)!=0:
    z = heapq.heappop(heap)
    if z[1] == goal:
      path.append(z[1])
      break
    path.append(z[1])
    for k,v in graph[z[1]].items():
      x = v+distance[z[1]]
      if k not in distance or x < distance[k]:
        distance[k] = x
        parent[k] = z[1]
        heapq.heappush(heap,(distance[k]+hueristic[k],k))
act_path = []
i = len(path)-1
act_path.append(path[i])
j=0
while True:
  act_path.append(parent[act_path[j]])
  i-=1
  j+=1
  if act_path[j] == start:
    break
act_path.reverse()
print("Path:",end=" ")
for i in range(len(act_path)):
  if goal not in path:
    print("NO PATH FOUND")
    break
  else:
    if i == len(act_path)-1:
      print(f"{act_path[i]}")
    else:
      print(f"{act_path[i]}--> ",end="")
if goal not in distance:
  print()
else:
  print(f"Total distance: {distance[goal]}")