# -*- coding: utf-8 -*-
"""cse422 lab 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/150hoxxLNJ9KX1PFOIpkNZC0X3f12Xi-r
"""

#task 1
import random
import math

def strength(x):
  strength_val = math.log(x+1,2) + (x/10)
  return strength_val

def utility(max_p,min_p):
  i = random.randint(0,1)
  random_value = random.randint(1,10)
  utility_val = strength(max_p) - strength(min_p) + (((-1)**i)*random_value)/10
  return utility_val

def minimax(depth,alpha,beta,max_p,min_p,maximizing):
  if depth == 5:
    return utility(max_p,min_p)

  if maximizing:
    branch = 2
    max_val = float('-inf')
    for i in range(branch):
      node_value = minimax(depth+1,alpha,beta,max_p,min_p,False)
      max_val = max(max_val,node_value)
      alpha = max(alpha,node_value)
      if beta <= alpha:
        break
    return max_val

  else:
    branch = 2
    min_val = float('inf')
    for i in range(branch):
      node_value = minimax(depth+1,alpha,beta,max_p,min_p,True)
      min_val = min(min_val,node_value)
      beta = min(beta,node_value)
      if beta <= alpha:
        break
    return min_val


def chess_game(starting_p,max_p,min_p,max_p_name,min_p_name):
  depth = 0
  alpha = float("-inf")
  beta = float("inf")
  final_val = minimax(depth,alpha,beta,max_p,min_p,True)
  if final_val > 0:
    winner = max_p_name
  elif final_val < 0:
    winner = min_p_name
  else:
    winner = "Draw"
  return [final_val,winner]

match_result = {"Magnus Carlsen" : 0, "Fabiano Caruana" : 0, "Draw" : 0}
starting_p = int(input("Enter starting player for game 1 (0 for Carlsen, 1 for Caruana): "))
strength_carlsen = float(input("Enter base strength for Carlsen: "))
strength_caruana = float(input("Enter base strength for Caruana: "))
game_round = 4

for j in range(game_round):
  if (starting_p + j) % 2 == 0:
    i = 0
    max_p = strength_carlsen
    max_p_name = "Magnus Carlsen"
    min_p = strength_caruana
    min_p_name = "Fabiano Caruana"
  else:
    i = 1
    max_p = strength_caruana
    max_p_name = "Fabiano Caruana"
    min_p = strength_carlsen
    min_p_name = "Magnus Carlsen"
  game_value = chess_game(starting_p,max_p,min_p,max_p_name,min_p_name)
  final_utility_val = game_value[0]
  winner = game_value[1]
  match_result[winner] += 1
  if i == 0:
    z= "(max)"
  else:
    z = "(min)"
  print(f"Game {i+1} winner: {winner} {z} (Utility value: {final_utility_val:.2f})")

print("Overall Result:")
print(f"Magnus Carlsen: {match_result['Magnus Carlsen']} wins")
print(f"Fabiano Caruana: {match_result['Fabiano Caruana']} wins")
print(f"Draw: {match_result['Draw']} games")
if match_result['Magnus Carlsen'] > match_result['Fabiano Caruana']:
  print("Overall Winner: Magnus Carlsen")
elif match_result['Fabiano Caruana'] > match_result['Magnus Carlsen']:
  print("Overall Winner: Fabiano Caruana")
else:
  print("Overall Winner: Draw")

#task2

import random
import math

def strength(x):
  strength_val = math.log(x+1,2) + (x/10)
  return strength_val

def utility(max_p,min_p):
  i = random.randint(0,1)
  random_value = random.randint(1,10)
  utility_val = strength(max_p) - strength(min_p) + (((-1)**i)*random_value)/10
  return utility_val


def minimax2(depth,alpha,beta,max_p,min_p,maximizing,mind_control):
  if depth == 5:
    return utility(max_p,min_p)
  if maximizing:
    branch = 2
    max_val = float("-inf")
    for i in range(branch):
      node_value = minimax2(depth+1,alpha,beta,max_p,min_p,False,mind_control)
      max_val = max(max_val,node_value)
      alpha = max(alpha,node_value)
      if beta <= alpha:
        break
    return max_val
  else:
    branch = 2
    if mind_control:
      min_val = float("-inf")
    else:
      min_val = float("inf")
    for i in range(branch):
      node_value = minimax2(depth+1,alpha,beta,max_p,min_p,False,mind_control)
      if mind_control:
        min_val = max(min_val,node_value)
      else:
        min_val = min(min_val,node_value)
      beta = min(beta,node_value)
      if beta <= alpha:
        break
    return min_val


def chess_noob_game(starting_p,mind_cost,max_p,min_p,max_p_name,min_p_name):
  depth = 0
  alpha = float("-inf")
  beta = float("inf")
  utility_without_mc = minimax2(depth,alpha,beta,max_p,min_p,True,False)
  utility_with_mc = minimax2(depth,alpha,beta,max_p,min_p,True,True)
  final_utility = utility_with_mc - mind_cost
  print(f'''

  ''')
  print(f"Minimax value without Mind Control: {utility_without_mc:.2f}")
  print(f"Minimax value with Mind Control: {utility_with_mc:.2f}")
  print(f"Minimax value with Mind Control after incurring the cost: {final_utility:.2f}")
  print(f'''

  ''')
  if utility_without_mc > 0:
    if final_utility>0:
      print(f"{max_p_name} should NOT use Mind Control as the position is already winning.")
    else:
      print(f"{max_p_name} should NOT use Mind Control as it backfires.")
  else:
    if final_utility>0:
      print(f"{max_p_name} should use Mind Control.")
    else:
      print(f"{max_p_name} should NOT use Mind Control as the position is losing either way.")


starting_p = int(input("Enter who goes first (0 for Light, 1 for L): "))
mind_cost = float(input("Enter the cost of using Mind Control: "))
strength_Light = float(input("Enter base strength for Light "))
strength_L = float(input("Enter base strength for L: "))

if starting_p == 0:
  max_p = strength_Light
  max_p_name = "Light"
  min_p = strength_L
  min_p_name = "L"
else:
  max_p = strength_L
  max_p_name = "L"
  min_p = strength_Light
  min_p_name = "Light"

chess_noob_game(starting_p,mind_cost,max_p,min_p,max_p_name,min_p_name)